### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by xuanxing666** [ashishkumar822/Jetson-SLAM#6]
1. Jetson-SLAM-master/src/cuda/orb_FAST_compute_score.cu(100): error: identifier "n_threads" is is undefined
      if(index < n_threads)
2. Jetson-SLAM-master/src/cuda/orb_FAST_compute_score.cu(100): error: identifier "n_threads" is  undefined
      if(index < n_threads)
3. Jetson-SLAM-master/src/cuda/orb_FAST_compute_score.cu(111): error: identifier "offset" is undefined 
 const unsigned char* ptr = image_data + offset;
and other issues like these。
How to resolve?
thanks！

**Comment by 593537505** [comment]
我的报错信息与你一致，请问你是否解决了呢

**Comment by 593537505** [comment]
I also encountered the same error message, may I ask if you have solved it

**Comment by xuanxing666** [comment]
还在解决中



---Original---
From: ***@***.***&gt;
Date: Sun, Nov 24, 2024 17:56 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ashishkumar822/Jetson-SLAM] Failed to compile (Issue #6)




 
我的报错信息与你一致，请问你是否解决了呢

**Comment by ashishkumar822** [comment]
Hi, Can you try compiling latest commit ? I dont see any compilation error. Which gcc and CUDA version are you using ?

**Comment by xuanxing666** [comment]
> Hi, Can you try compiling latest commit ? I dont see any compilation error. Which gcc and CUDA version are you using ?

CUDA version: 12.2
gcc version: 9.4.0

My computer system is ubuntu20.04 and the architecture is AMD.

**Comment by xuanxing666** [comment]
> Hi, Can you try compiling latest commit ? I dont see any compilation error. Which gcc and CUDA version are you using ?

For reasons using ubuntu20.04 the compilation needs to rely on c++14 and I added the configuration in CMakeLists.txt and the relevant header file(pcl/console/print.h)

**Comment by xuanxing666** [comment]
> Hi, Can you try compiling latest commit ? I dont see any compilation error. Which gcc and CUDA version are you using ?

in orb_FAST_compute_score.cu, Please help confirm whether there is a missing "}" belonging to "namespace orb_cuda {"

**Comment by ashishkumar822** [comment]
> > Hi, Can you try compiling latest commit ? I dont see any compilation error. Which gcc and CUDA version are you using ?
> 
> CUDA version: 12.2 gcc version: 9.4.0
> 
> My computer system is ubuntu20.04 and the architecture is AMD.

Its alright. It won't matter. AMD x86_64 arch will work. No worries.

**Comment by ashishkumar822** [comment]
> > Hi, Can you try compiling latest commit ? I dont see any compilation error. Which gcc and CUDA version are you using ?
> 
> in orb_FAST_compute_score.cu, Please help confirm whether there is a missing "}" belonging to "namespace orb_cuda {"

That's why I said, Please try the new commit. It has all the C++14 flags tested and there is no build error.

**Comment by ashishkumar822** [comment]
> > Hi, Can you try compiling latest commit ? I dont see any compilation error. Which gcc and CUDA version are you using ?
> 
> in orb_FAST_compute_score.cu, Please help confirm whether there is a missing "}" belonging to "namespace orb_cuda {"

No, there is not any missing '{'. It is being thrown due to the incompatibility of the Host compiler (gcc/g++) and CUDA compiler (NVCC).

**Comment by xuanxing666** [comment]
OK，Thanks



---Original---
From: "Ashish ***@***.***&gt;
Date: Wed, Nov 27, 2024 17:55 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ashishkumar822/Jetson-SLAM] Failed to compile (Issue #6)




   
Hi, Can you try compiling latest commit ? I dont see any compilation error. Which gcc and CUDA version are you using ?
  
in orb_FAST_compute_score.cu, Please help confirm whether there is a missing "}" belonging to "namespace orb_cuda {"
  
No, there is not any missing '{'. It is being thrown due to the incompatibility of the Host compiler (gcc/g++) and CUDA compiler (NVCC).
